// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate-job-index.ts
// Run 'bun run generate:jobs' to regenerate this file

import type { JobTasks } from './types.js';

import aiSdk from './jobs/ai-sdk.js';
import betterAuth from './jobs/better-auth.js';
import nextJs16 from './jobs/next-js-16.js';
import polarSh from './jobs/polar-sh.js';
import prisma from './jobs/prisma.js';
import react19 from './jobs/react-19.js';
import trpc from './jobs/trpc.js';
import zod from './jobs/zod.js';

/**
 * Registry of all available crawl jobs.
 * Each job contains one or more tasks (crawl configurations).
 */
export const jobs = {
	'ai-sdk': aiSdk,
	'better-auth': betterAuth,
	'next-js-16': nextJs16,
	'polar-sh': polarSh,
	prisma,
	'react-19': react19,
	trpc,
	zod,
} satisfies Record<string, JobTasks>;

export type JobRegistry = typeof jobs;
