name: Release workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Checkout main branch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Bun'
        uses: oven-sh/setup-bun@v2

      - name: 'Cache Bun dependencies'
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 'Install dependencies'
        run: bun install --frozen-lockfile

      - name: 'Build project'
        run: bun run build

      - name: 'Run semantic release'
        run: bun run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
